# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait


class Test10():
    def setup_method(self, method):
        self.driver = webdriver.Remote(command_executor='http://localhost:4444/wd/hub',
                                       desired_capabilities=DesiredCapabilities.CHROME)
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_10(self):
        self.driver.get("http://aiweinewtest.zizaicloud.cn//login")
        self.driver.set_window_size(1724, 1055)
        self.driver.find_element(By.CSS_SELECTOR, ".ivu-input-type-text > .ivu-input").click()
        self.driver.find_element(By.CSS_SELECTOR, ".ivu-input-type-text > .ivu-input").send_keys("admin87654321")
        self.driver.find_element(By.CSS_SELECTOR, ".ivu-input-type-password > .ivu-input").click()
        self.driver.find_element(By.CSS_SELECTOR, ".ivu-input-type-password > .ivu-input").send_keys("Workeasy2018.")
        self.driver.find_element(By.CSS_SELECTOR, ".ivu-btn").click()
        element = self.driver.find_element(By.CSS_SELECTOR, ".ivu-btn")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).perform()
        self.driver.find_element(By.CSS_SELECTOR, ".icon-box:nth-child(2) > .text-left:nth-child(1) > span").click()
        self.driver.find_element(By.CSS_SELECTOR, ".modal > .ivu-form .ivu-input").click()
        self.driver.find_element(By.CSS_SELECTOR, ".modal > .ivu-form .ivu-input").click()
        self.driver.find_element(By.CSS_SELECTOR, ".modal > .ivu-form .ivu-input").click()
        self.driver.find_element(By.CSS_SELECTOR, ".modal > .ivu-form .ivu-input").send_keys("自动化测试任务")
        self.driver.find_element(By.CSS_SELECTOR, ".fixed6 .ivu-input").click()
        self.driver.execute_script("window.scrollTo(0,0)")
        self.driver.find_element(By.XPATH,
                                 "/html/body/div[57]/div[2]/div/div/div[1]/div/div[1]/div[2]/ul[7]/li/ul[1]/li/span[2]/span/span/span").click()
        element = self.driver.find_element(By.CSS_SELECTOR, ".fixed6 .ivu-input")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).click_and_hold().perform()
        self.driver.find_element(By.CSS_SELECTOR, "body").click()
        self.driver.find_element(By.XPATH,
                                 "//div[57]/div[2]/div/div/div/div/div/div[2]/ul[7]/li/ul/li/span[2]/span/span/span").click()
        self.driver.find_element(By.XPATH, "//div[57]/div[2]/div/div/div[2]/div/div[2]/button[2]/span").click()
        self.driver.find_element(By.CSS_SELECTOR, ".footer-box:nth-child(2) .ivu-switch").click()
        self.driver.find_element(By.XPATH,
                                 "//*[@id=\"app\"]/div/div[2]/div[2]/div/div[2]/div[1]/div[3]/div/div[1]/div[3]/div/div/section/ol/li/i").click()
        element = self.driver.find_element(By.XPATH,
                                           "//*[@id=\"app\"]/div/div[2]/div[2]/div/div[2]/div[1]/div[3]/div/div[1]/div[3]/div/div/section/ol/li/i")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).perform()
        element = self.driver.find_element(By.CSS_SELECTOR, "body")
        actions = ActionChains(self.driver)
        actions.move_to_element(element, 0, 0).perform()
        self.driver.execute_script("window.scrollTo(0,0)")
        self.driver.find_element(By.CSS_SELECTOR, "ol").click()
        self.driver.find_element(By.CSS_SELECTOR, ".dot:nth-child(2)").click()
        self.driver.find_element(By.CSS_SELECTOR, ".ivu-input-type-textarea:nth-child(2) > .ivu-input").click()
        self.driver.find_element(By.CSS_SELECTOR, ".ivu-input-type-textarea:nth-child(2) > .ivu-input").send_keys(
            "1、完成了测试")
        self.driver.find_element(By.XPATH, "//div[2]/input").click()
        self.driver.find_element(By.XPATH, "//div[2]/input").send_keys("8")
        self.driver.find_element(By.CSS_SELECTOR, ".log-modal .ivu-btn:nth-child(2) > span").click()
        self.driver.find_element(By.CSS_SELECTOR, ".ivu-avatar-string").click()
        self.driver.find_element(By.CSS_SELECTOR, ".ivu-avatar-string").click()
        self.driver.find_element(By.CSS_SELECTOR, ".cl_ul_li:nth-child(3)").click()
        self.driver.find_element(By.CSS_SELECTOR, ".ivu-btn-text:nth-child(2) > span").click()
        self.driver.find_element(By.CSS_SELECTOR, ".ivu-form:nth-child(2) .ivu-input-wrapper > .ivu-input").click()
        self.driver.find_element(By.CSS_SELECTOR, ".ivu-form:nth-child(2) .ivu-input-wrapper > .ivu-input").send_keys(
            "任务提交备注")
        self.driver.find_element(By.CSS_SELECTOR, ".v-transfer-dom:nth-child(25) .ivu-btn-primary > span").click()
        self.driver.find_element(By.CSS_SELECTOR, ".detail_content_container").click()
        self.driver.find_element(By.CSS_SELECTOR, ".TimelineItem > .ivu-btn:nth-child(2)").click()
        self.driver.find_element(By.CSS_SELECTOR, ".ivu-input-number-focused .ivu-input-number-input").click()
        self.driver.find_element(By.CSS_SELECTOR, ".ivu-input-number-focused .ivu-input-number-input").send_keys("10")
        self.driver.find_element(By.CSS_SELECTOR,
                                 ".ivu-modal-body > .ivu-form > .ivu-form-item:nth-child(2) .ivu-input").click()
        self.driver.find_element(By.CSS_SELECTOR,
                                 ".ivu-modal-body > .ivu-form > .ivu-form-item:nth-child(2) .ivu-input").send_keys("很好")
        self.driver.find_element(By.CSS_SELECTOR, ".foot-container .ivu-btn-primary > span").click()
        self.driver.find_element(By.CSS_SELECTOR, ".foot-container .ivu-btn-primary > span").click()
        self.driver.execute_script("window.scrollTo(0,0)")

